# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [2]:
df = pd.read_csv("data/Aviation_Data.csv", low_memory=False)
print(df.shape)
df.head()

(88889, 31)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [3]:
df.isna().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [4]:
df.dtypes

Event.Id                      str
Investigation.Type            str
Accident.Number               str
Event.Date                    str
Location                      str
Country                       str
Latitude                      str
Longitude                     str
Airport.Code                  str
Airport.Name                  str
Injury.Severity               str
Aircraft.damage               str
Aircraft.Category             str
Registration.Number           str
Make                          str
Model                         str
Amateur.Built                 str
Number.of.Engines         float64
Engine.Type                   str
FAR.Description               str
Schedule                      str
Purpose.of.flight             str
Air.carrier                   str
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition             str
Broad.phase.of.flight         str
Report.Status                 str
Publication.Date              str
dtype: object

In [5]:
df.describe(include="all")

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
count,88889,88889,88889,88889,88837,88663,34382,34373,50132,52704,...,82697,16648,77488.000000,76379.000000,76956.000000,82977.000000,84397,61724,82505,75118
unique,87951,2,88863,14782,27758,219,25589,27154,10374,24870,...,26,13590,NaN,NaN,NaN,NaN,4,12,17074,2924
top,20001214X45071,Accident,ERA22LA103,1982-05-16,"ANCHORAGE, AK",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,NaN,NaN,NaN,NaN,VMC,Landing,Probable Cause,25-09-2020
freq,3,85015,2,25,434,82248,19,24,1488,240,...,49448,258,NaN,NaN,NaN,NaN,77303,15428,61754,17019
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.647855,0.279881,0.357061,5.325440,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.485960,1.544084,2.235625,27.913634,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,2.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,349.000000,161.000000,380.000000,699.000000,NaN,NaN,NaN,NaN

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [6]:
# Make the column names easier to type
df.columns = df.columns.str.strip().str.lower()

In [7]:
#checking for airplanes only
df["aircraft.category"].unique()

<StringArray>
[                nan,          'Airplane',        'Helicopter',
            'Glider',           'Balloon',         'Gyrocraft',
        'Ultralight',           'Unknown',             'Blimp',
      'Powered-Lift',      'Weight-Shift', 'Powered Parachute',
            'Rocket',              'WSFT',               'UNK',
              'ULTR']
Length: 16, dtype: str

In [8]:
df = df[df['aircraft.category'] == "Airplane"]

In [9]:
#inspecting for column to show airplanes only
df["amateur.built"].unique()

<StringArray>
['No', 'Yes', nan]
Length: 3, dtype: str

In [10]:
df = df[df["amateur.built"] == "No"]

In [11]:
# The data ends in 2022, so keep events from 1983 onward (about 40 years).
df["event.date"] = pd.to_datetime(df["event.date"], errors="coerce")
df = df[df["event.date"] >= "1983-01-01"]

In [12]:
df.isna().sum()

event.id                      0
investigation.type            0
accident.number               0
event.date                    0
location                      6
country                       1
latitude                   2278
longitude                  2284
airport.code               7464
airport.name               7377
injury.severity             813
aircraft.damage            1227
aircraft.category             0
registration.number         206
make                          3
model                        18
amateur.built                 0
number.of.engines          2551
engine.type                3956
far.description             480
schedule                  18926
purpose.of.flight          3680
air.carrier               11285
total.fatal.injuries       2750
total.serious.injuries     2828
total.minor.injuries       2544
total.uninjured             711
weather.condition          2979
broad.phase.of.flight     18619
report.status              4663
publication.date            957
dtype: int64

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [13]:
#inspecting relevant columns first
df[["total.fatal.injuries","total.serious.injuries","total.minor.injuries","total.uninjured"]].isna().sum()

total.fatal.injuries      2750
total.serious.injuries    2828
total.minor.injuries      2544
total.uninjured            711
dtype: int64

In [14]:
# Convert injury counts to numbers, then treat blank counts as zero for this estimate.
injury_columns = ["total.fatal.injuries", "total.serious.injuries", "total.minor.injuries", "total.uninjured"]
for column in injury_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")
df[injury_columns] = df[injury_columns].fillna(0)

# Estimate people on board from the reported injury counts.
df["total_passengers"] = df[injury_columns].sum(axis=1)
df["total_passengers"].describe()

count    21447.000000
mean         8.592297
std         35.910084
min          0.000000
25%          1.000000
50%          2.000000
75%          2.000000
max        588.000000
Name: total_passengers, dtype: float64

In [15]:
# Fatal and serious injuries divided by estimated people on board.
df["serious_injury_fatality_rate"] = (df["total.fatal.injuries"] + df["total.serious.injuries"]) / df["total_passengers"].replace(0, np.nan)
df["serious_injury_fatality_rate"].describe()

count    20543.000000
mean         0.283971
std          0.431704
min          0.000000
25%          0.000000
50%          0.000000
75%          0.800000
max          1.000000
Name: serious_injury_fatality_rate, dtype: float64

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

### Aircraft damage cleaning

I removed extra spaces from damage labels. I made `aircraft.destroyed` equal to 1 when the aircraft was destroyed and 0 when damage was minor or substantial. Blank and `Unknown` damage stays missing because we cannot tell whether the aircraft was destroyed.

In [16]:
#checking for aircraft damage
df["aircraft.damage"].value_counts(dropna = False   )

aircraft.damage
Substantial    16990
Destroyed       2316
NaN             1227
Minor            817
Unknown           97
Name: count, dtype: int64

In [17]:
# Remove spaces and check the labels
df["aircraft.damage"] = df["aircraft.damage"].str.strip()
df["aircraft.damage"].value_counts(dropna=False)

aircraft.damage
Substantial    16990
Destroyed       2316
NaN             1227
Minor            817
Unknown           97
Name: count, dtype: int64

In [18]:
# Make a simple 1/0 measure for whether the aircraft was destroyed.
df["aircraft.destroyed"] = df["aircraft.damage"].map({"Destroyed": 1, "Substantial": 0, "Minor": 0})

In [19]:
df["aircraft.destroyed"].value_counts(dropna=False)

aircraft.destroyed
0.0    17807
1.0     2316
NaN     1324
Name: count, dtype: int64

In [20]:
# Overall fraction of known damage records where the aircraft was destroyed
df["aircraft.destroyed"].mean()

np.float64(0.11509218307409431)

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [21]:
df["make"].value_counts(dropna=False)

make
CESSNA               4867
PIPER                2803
Cessna               2279
Piper                1186
BOEING               1037
                     ...
BELL                    1
DETRICK DONALD G        1
PHANTOM                 1
JAMES R DERNOVSEK       1
ORLICAN S R O           1
Name: count, Length: 1333, dtype: int64

In [22]:
df["make"].nunique(dropna=True)

1332

### Cleaning the Make column

- Remove spaces before and after each name.
- Use capital letters so the same manufacturer is not counted more than once.
- Keep missing names missing.
- Keep makes with at least 50 records, as suggested in the assignment.

In [23]:
df["make"] = df["make"].str.strip()

In [24]:
df["make"] = df["make"].str.upper()

In [25]:
#finding make counts
make_counts = df["make"].value_counts()

In [26]:
#finding counts more than 50
valid_makes = make_counts[make_counts >= 50].index

In [27]:
#filtering the dataframe
df = df[df["make"].isin(valid_makes)]

In [28]:
#checking result
df["make"].value_counts()

make
CESSNA                            7146
PIPER                             3989
BEECH                             1431
BOEING                            1264
MOONEY                             363
AIRBUS                             243
CIRRUS DESIGN CORP                 220
BELLANCA                           219
AIR TRACTOR INC                    219
MAULE                              215
AIR TRACTOR                        206
AERONCA                            200
CHAMPION                           158
EMBRAER                            153
GRUMMAN                            147
LUSCOMBE                           141
CIRRUS                             137
STINSON                            129
MCDONNELL DOUGLAS                  108
NORTH AMERICAN                     106
DEHAVILLAND                         95
TAYLORCRAFT                         93
AERO COMMANDER                      90
AVIAT AIRCRAFT INC                  76
SOCATA                              75
DIAMOND AIRCRAFT IND INC            74
DE HAVILLAND                        73
AVIAT                               70
BOMBARDIER INC                      65
RAYTHEON AIRCRAFT COMPANY           62
ROCKWELL INTERNATIONAL              58
GRUMMAN ACFT ENG COR-SCHWEIZER      58
AYRES                               55
ERCOUPE                             52
AMERICAN CHAMPION AIRCRAFT          52
BOMBARDIER                          50
Name: count, dtype: int64

### Inspect the Model column

Drop records without a make or model. A model name can be used by more than one make, so create `aircraft.type` by joining the make and model.

In [29]:
#check for isna values in both make and model columns
df[["make", "model"]].isna().sum()

make      0
model    13
dtype: int64

In [30]:
#dropping the isna values
df = df.dropna(subset=["make", "model"])

In [31]:
#inspecting the columns and counts
df["make"].nunique()

36

In [32]:
df["model"].nunique()

2034

In [33]:
df["make"].value_counts()

make
CESSNA                            7142
PIPER                             3988
BEECH                             1431
BOEING                            1261
MOONEY                             363
AIRBUS                             243
CIRRUS DESIGN CORP                 220
BELLANCA                           219
AIR TRACTOR INC                    219
MAULE                              215
AIR TRACTOR                        206
AERONCA                            200
CHAMPION                           158
EMBRAER                            152
GRUMMAN                            147
LUSCOMBE                           141
CIRRUS                             137
STINSON                            129
MCDONNELL DOUGLAS                  108
NORTH AMERICAN                     106
DEHAVILLAND                         95
TAYLORCRAFT                         93
AERO COMMANDER                      90
AVIAT AIRCRAFT INC                  76
SOCATA                              75
DIAMOND AIRCRAFT IND INC            74
DE HAVILLAND                        72
AVIAT                               70
BOMBARDIER INC                      65
RAYTHEON AIRCRAFT COMPANY           62
ROCKWELL INTERNATIONAL              58
GRUMMAN ACFT ENG COR-SCHWEIZER      58
AYRES                               52
ERCOUPE                             52
AMERICAN CHAMPION AIRCRAFT          52
BOMBARDIER                          50
Name: count, dtype: int64

In [34]:
df["model"].value_counts()

model
172            769
737            403
152            316
182            304
172S           276
              ...
T206G            1
BD-700-2A12      1
737-8            1
P206D            1
PA-44            1
Name: count, Length: 2034, dtype: int64

In [35]:
df[["make","model"]].value_counts()

make            model
CESSNA          172            769
BOEING          737            403
CESSNA          152            316
                182            304
                172S           276
                              ...
                T206G            1
BOMBARDIER INC  BD-700-2A12      1
BOEING          737-8            1
CESSNA          P206D            1
PIPER           PA-44            1
Name: count, Length: 2159, dtype: int64

In [36]:
# Combine make and model so each plane type has a clear name
df["aircraft.type"] = df["make"] + "_" + df["model"]

In [37]:
#inspecting
df["aircraft.type"].value_counts()

aircraft.type
CESSNA_172                    769
BOEING_737                    403
CESSNA_152                    316
CESSNA_182                    304
CESSNA_172S                   276
                             ...
CESSNA_T206G                    1
BOMBARDIER INC_BD-700-2A12      1
BOEING_737-8                    1
CESSNA_P206D                    1
PIPER_PA-44                     1
Name: count, Length: 2159, dtype: int64

### Cleaning other columns

I checked engine type, weather, number of engines, purpose of flight, and phase of flight. I removed extra spaces and changed placeholder labels such as `Unknown` and `UNK` to missing values. I left missing values as missing because there is not enough information to fill them accurately.

In [38]:
df["engine.type"].value_counts(dropna=False)

engine.type
Reciprocating      12835
NaN                 3214
Turbo Prop           931
Turbo Fan            701
Unknown              105
Turbo Jet             71
Geared Turbofan       12
Turbo Shaft            9
UNK                    1
Name: count, dtype: int64

In [39]:
# Remove extra spaces and make placeholder values missing
df["engine.type"] = df["engine.type"].str.strip()
df["engine.type"] = df["engine.type"].replace(["Unknown", "UNK", "Unk", "N/A", "NA"], np.nan)
for column in ["weather.condition", "purpose.of.flight", "broad.phase.of.flight"]:
    df[column] = df[column].str.strip()
    df[column] = df[column].replace(["Unknown", "UNK", "Unk", "N/A", "NA"], np.nan)
df["number.of.engines"] = pd.to_numeric(df["number.of.engines"], errors="coerce")
df.loc[df["number.of.engines"] == 0, "number.of.engines"] = np.nan
df[["engine.type", "weather.condition", "number.of.engines", "purpose.of.flight", "broad.phase.of.flight"]].isna().sum()

engine.type               3320
weather.condition         2679
number.of.engines         2094
purpose.of.flight         3350
broad.phase.of.flight    15438
dtype: int64

### Column Removal

The assignment says to keep columns with more than 20,000 non-missing values. I checked the counts below. I also keep the injury, damage, make/model, and incident-factor columns needed for Part Two, even when they have fewer than 20,000 values.

In [40]:
# Count non-missing values in each column
non_missing_counts = df.notna().sum().sort_values()
non_missing_counts

schedule                         2139
broad.phase.of.flight            2441
air.carrier                      8448
airport.code                    11648
airport.name                    11754
report.status                   14094
purpose.of.flight               14529
engine.type                     14559
weather.condition               15200
number.of.engines               15785
longitude                       15978
latitude                        15981
aircraft.destroyed              16733
aircraft.damage                 16815
publication.date                17091
serious_injury_fatality_rate    17103
injury.severity                 17162
far.description                 17535
registration.number             17715
location                        17875
country                         17878
accident.number                 17879
event.date                      17879
aircraft.category               17879
model                           17879
make                            17879
total.fatal.injuries            17879
amateur.built                   17879
total.uninjured                 17879
total.minor.injuries            17879
investigation.type              17879
event.id                        17879
total_passengers                17879
total.serious.injuries          17879
aircraft.type                   17879
dtype: int64

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [41]:
# Keep columns with more than 20,000 values, plus fields needed in Part Two.
columns_for_analysis = ["event.date", "make", "model", "aircraft.type", "total.fatal.injuries", "total.serious.injuries", "total.minor.injuries", "total.uninjured", "total_passengers", "serious_injury_fatality_rate", "aircraft.damage", "aircraft.destroyed", "weather.condition", "engine.type", "number.of.engines", "purpose.of.flight", "broad.phase.of.flight"]
columns_with_many_values = non_missing_counts[non_missing_counts > 20000].index.tolist()
columns_to_keep = columns_with_many_values.copy()
for column in columns_for_analysis:
    if column not in columns_to_keep:
        columns_to_keep.append(column)
df = df[columns_to_keep]
df.to_csv("outputs/aviation_accidents_cleaned.csv", index=False)
print("Saved cleaned data:", df.shape)

Saved cleaned data: (17879, 17)